version: '3.4'

networks:
  app-network:
    driver: bridge

services:
  burgerroyale.api:
    build:
      context: .
      dockerfile: BurgerRoyale/Dockerfile
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Server=db,1433;Database=BurgerRoyaleDb;User Id=SA;TrustServerCertificate=True;Password='65876Df&';
      - PaymentService__BaseUrl=fakepaymentservice.api
    ports:
      - "5000:80"
    networks:
      - app-network

  fakepaymentservice.api:
    build:
      context: .
      dockerfile: FakePaymentService/Dockerfile
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Server=db,1433;Database=FakePaymentMicroserviceDb;User Id=SA;TrustServerCertificate=True;Password='65876Df&';
    ports:
      - "5001:80"
    networks:
      - app-network

  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "65876Df&"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - db-data:/var/opt/mssql
    networks:
      - app-network
  
volumes:
  db-data: