apiVersion: apps/v1
kind: Deployment
metadata:
  name: fakepayment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: fakepayment
    spec:
      containers:
        - name: fakepayment
          image: douglasfuelber/fake-payment-service:latest
          ports:
            - containerPort: 5001
              protocol: TCP
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: ASPNETCORE_URLS
              value: http://*:5001
            - name: ConnectionStrings__DefaultConnection
              value: Server=mssqlserver-service;Database=FakePaymentMicroserviceDb;User Id=SA;TrustServerCertificate=True;Password='65876Df&';
          resources:
            requests:
              memory: "128Mi"
              cpu: "200m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          volumeMounts:
            - name: tz-config
              mountPath: /etc/localtime
      volumes:
        - name: tz-config
          hostPath:
            path: /usr/share/zoneinfo/America/Sao_Paulo
  selector:
    matchLabels:
      app: fakepayment