apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssqlserver-pvc
  labels:
    name: mssqlserver-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
