apiVersion: v1
kind: PersistentVolume
metadata:
  name: mssqlserver-pv
  labels:
    name: mssqlserver-pv
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /run/desktop/mnt/host/c/dados/kubernetes
